###

GET http://0.0.0.0:3000/student/

###

GET http://0.0.0.0:3000/student?name=John

###

POST http://0.0.0.0:3000/student
Content-Type: application/json

{
    "name": "John",
    "age": 25,
    "_id": "258525852"
}

###

PUT http://0.0.0.0:3000/student

###

DELETE http://0.0.0.0:3000/student
